### ISSUE TITLE
Trigger A leaves me in visual mode, I want it to leave me in insert mode instead

### ISSUE THREAD

**Issue by vasko-deb** [draivin/hsnips#28] opened 2020-09-24 10:21 UTC
Hi, I really love the extension, there is one issue for me. I am not sure whether it is caused by hsnips or by my vscode-vim settings somehow. 

I have a snippet like:

snippet eq "Equation" b
\begin{equation}
    $1
\end{equation}
$0
endsnippet

which works exactly as expected, places the cursor in position $1 and vim is in insert mode. However, if I use an automatic trigger like

snippet eq "Equation" bA
\begin{equation}
    $1
\end{equation}
$0
endsnippet

the snippet still expands as before however vim is in visual mode and the cursor is placed just somewhere. Then to proceed, I shall navigate with hjkl to the place $1, press ECS to enter normal mode, then press i to enter insert mode and only then the snippet works as expected.

So my question is where are the settings that tell vscode-vim in which mode to be after the snippet is expanded?

**Comment by draivin** [comment] 2020-09-25 10:31
That's weird, I can't seem to reproduce the issue, currently there is no support for the `b` flag, could you check if it works when you remove it? In any case, I just merged a commit implementing that flag, and I will publish the new version soon.

**Comment by draivin** [comment] 2020-09-25 10:46
Right, I just updated my vscode and extensions, and now I'm hitting the issue as well, it seems to be caused by `vscodevim` version 1.17, so rolling back to 1.16 fixes it for now, I'll look into this issue and see what I can do.

**Closed** 2021-01-23 19:17 UTC
