### ISSUE TITLE
the snippets will be triggered under Chinese input mode

### ISSUE THREAD

**Issue by lancerXXXX** [draivin/hsnips#26] opened 2020-07-21 03:25 UTC
![image](https://user-images.githubusercontent.com/42160297/88009274-b0a46580-cb44-11ea-9b6c-ccf547a801c4.png)

This kind of problem never happened before.

**Comment by lancerXXXX** [comment] 2020-07-21 03:55
my operating system is win10

**Comment by draivin** [comment] 2020-07-22 01:29
What do you mean by the snippets are triggered? What is the expected behavior here? And what did actually happen?

**Comment by lancerXXXX** [comment] 2020-07-22 01:43
![test2](https://user-images.githubusercontent.com/42160297/88124187-1f45f980-cbff-11ea-8fd9-a092b59a184a.gif)

when I type in English mode, the `kuang` will be triggered to become `testForthisproblem`

but when I type in Chinese mode, I want to print `方框` which means box in English, 
for this, I have to type `fangkuang`, but the `kuang` will be triggered,


In my impression, this situation has never happened before

**Comment by draivin** [comment] 2020-07-23 00:52
I changed the way we handle automatic snippet expansions, as it is now, I'd have to look for a way to detect if you are using the chinese input mode, and if so ignore the auto completions. Do you know of such a library? I honestly have no idea where to start looking. How can I trigger the chinese input mode myself?

**Comment by lancerXXXX** [comment] 2020-07-23 01:02
I really wanna help, but I have no idea at all.😅

**Comment by draivin** [comment] 2020-07-23 01:07
Is the chinese input an external program or is it native to your OS?

**Comment by lancerXXXX** [comment] 2020-07-23 01:10
It comes with Win10.

**Comment by sffred** [comment] 2021-12-01 06:21
I know what the issue @lancerXXXX  is facing. He is using the Microsoft IME which will turn your typed english characters into Chinese, but those English words will appear in the vscode typing area first so it will be detected by hypersnips. I think that is issue is hard to fix because it is just how the IME works. Maybe you can detect the state of input method but... hard to say if it's a good idea.

**Comment by draivin** [comment] 2021-12-02 22:36
Thanks for the feedback @sffred, I guess this is out of scope for this extension then, if anyone is facing this issue I'd suggest to change the snippet activation to Chinese characters, or otherwise to avoid using English word activations that would conflict with the IME keyboard.

**Closed by draivin** 2021-12-02 22:36 UTC
