### ISSUE TITLE
Option to access selected text, before the snippet was triggered

### ISSUE THREAD

**Issue by oiiiiiiii** [draivin/hsnips#137] opened 2022-11-13 15:31 UTC
In VSCode default snippets if have the option to access previously selected text with `$TM_SELECTED_TEXT`. Is there something similar for hsnips or at a workaround to achieve that?

**Comment by gruvw** [comment] 2022-11-13 16:02
Duplicate of #81

**Comment by draivin** [comment] 2022-12-22 10:46
Closing as duplicate.

**Closed by draivin** 2022-12-22 10:46 UTC
